<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Psychology R Bootcamp - 4: Insights from data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-making-decisions.html" rel="next">
<link href="./03-exploring-data.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="styles.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./00-getting-started.html">Lessons</a></li><li class="breadcrumb-item"><a href="./04-insights-from-data.html">4: Insights from data</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Psychology R Bootcamp</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homepage</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Lessons</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">0: Getting started</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1: R basics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2: Working with data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-exploring-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3: Exploring data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-insights-from-data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">4: Insights from data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-making-decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5: Making decisions</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./next.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What’s next</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About us</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#investigation-body-temperature" id="toc-investigation-body-temperature" class="nav-link active" data-scroll-target="#investigation-body-temperature">Investigation: Body temperature</a></li>
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses">Hypotheses</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#statistics-vary-from-sample-to-sample" id="toc-statistics-vary-from-sample-to-sample" class="nav-link" data-scroll-target="#statistics-vary-from-sample-to-sample">Statistics vary from sample to sample</a></li>
  <li><a href="#t-test-for-a-mean" id="toc-t-test-for-a-mean" class="nav-link" data-scroll-target="#t-test-for-a-mean">T-test for a mean</a></li>
  <li><a href="#p-value" id="toc-p-value" class="nav-link" data-scroll-target="#p-value">P-value</a></li>
  <li><a href="#confidence-interval" id="toc-confidence-interval" class="nav-link" data-scroll-target="#confidence-interval">Confidence interval</a></li>
  <li><a href="#effect-size-cohens-d" id="toc-effect-size-cohens-d" class="nav-link" data-scroll-target="#effect-size-cohens-d">Effect size: Cohen’s D</a></li>
  <li><a href="#validity-conditions-of-the-t-test" id="toc-validity-conditions-of-the-t-test" class="nav-link" data-scroll-target="#validity-conditions-of-the-t-test">Validity conditions of the t-test</a></li>
  <li><a href="#recommended-activities" id="toc-recommended-activities" class="nav-link" data-scroll-target="#recommended-activities">Recommended activities</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">4: Insights from data</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="investigation-body-temperature" class="level2"><h2 class="anchored" data-anchor-id="investigation-body-temperature">Investigation: Body temperature</h2>
<blockquote class="blockquote">
<p><strong>Research question</strong></p>
<p>Has the average body temperature for healthy humans changed from the long-thought 37 °C?</p>
</blockquote>
<p>You might think that the average body temperature for healthy humans is about 37 °C. This is what most people would say and it kind of has been given for granted for many years.<br>
However, could it be possible that the average body temperature for healthy humans has changed over time? Perhaps this could be due to the climate change?<br>
We will use data<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> comprising measurements on body temperature and pulse rate for a random sample of <span class="math inline">\(n = 50\)</span> healthy subjects. The data are available <a href="data/BodyTemp.csv">here</a> and also at the following address: <a href="https://uoepsy.github.io/data/BodyTemp.csv" class="uri">https://uoepsy.github.io/data/BodyTemp.csv</a></p>
</section><section id="hypotheses" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="hypotheses">Hypotheses</h2>
<p>The first step is to translate the research question into hypothesis. This can be tricky sometimes and it involves understanding the research question.</p>
<p>The mean for an entire population is commonly denoted with the Greek symbol <span class="math inline">\(\mu\)</span> (pronounced mu). In loose terms we want to test whether the mean body temperature for all healthy humans is 37 °C or if it has changed in either direction (i.e.&nbsp;it is higher or lower).</p>
<p>In formal notation, we will investigate the following null and alternative hypotheses:</p>
<p><span class="math display">\[H_0 : \mu = 37 °C\]</span> <span class="math display">\[H_1 : \mu \neq 37 °C\]</span></p>
<p>The null hypothesis (<span class="math inline">\(H_0\)</span>) represents the status quo, i.e.&nbsp;what is the currently accepted standard. The alternative hypothesis (<span class="math inline">\(H_1\)</span>) typically encodes our research question.</p>
<aside>
null hypothesis<br>
alternative hypothesis
</aside></section><section id="data" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="data">Data</h2>
<p>First, we need to read the data into R.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">btdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">'data/BodyTemp.csv'</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">btdata</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  BodyTemp Pulse
     &lt;dbl&gt; &lt;dbl&gt;
1     36.4    69
2     37.4    77
3     37.2    75
4     37.1    84
5     36.7    71
6     37.2    76</code></pre>
</div>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">btdata</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50  2</code></pre>
</div>
</div>
<p>From the output above we see that we have measuremenets on 2 variables (BodyTemp and Pulse) on 50 participants.</p>
<p>Let’s visualise the variable of interest, BodyTemp:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">btdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">BodyTemp</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">'white'</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">'Body temperature'</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04-insights-from-data_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Next, we numerically describe the variable of interest, BodyTemp:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">btstats</span> <span class="op">&lt;-</span> <span class="va">btdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>        Min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">BodyTemp</span><span class="op">)</span>,</span>
<span>        Med <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">BodyTemp</span><span class="op">)</span>,</span>
<span>        M <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">BodyTemp</span><span class="op">)</span>,</span>
<span>        SD <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">BodyTemp</span><span class="op">)</span>,</span>
<span>        Max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">BodyTemp</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span></span>
<span><span class="va">btstats</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
    Min   Med     M    SD   Max
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  35.8  36.8  36.8 0.425  38.2</code></pre>
</div>
</div>
<p>The numbers above are numerical descriptions of the body temperatures in the collected sample of 50 healthy subjects. Any number which summarises data in a sample is called a <em>statistic</em> (short for sample characteristic). The two most famous statistics are probably the sample mean (or average) <span class="math inline">\(M = 36.81\)</span> and the standard deviation <span class="math inline">\(SD = 0.43\)</span>.</p>
<aside>
statistic
</aside><p>On a completely different level lies the concept of <em>parameter</em>, which is any number describing the whole population. Often, we do not have data for the entire population, and hence the parameter is <em>unknown.</em></p>
<aside>
parameter
</aside><p>When we want to investigate a research question, we typically obtain a sample from the entire population, then collect data from the participants in the sample, and use the sample statistic as our <em>best estimate</em> of the unknown population parameter.<br>
The process of drawing conclusions about the entire population using only a subset of the data (the sample) is called <em>(statistical) inference</em>.</p>
<aside>
best estimate<br>
statistical inference
</aside></section><section id="statistics-vary-from-sample-to-sample" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="statistics-vary-from-sample-to-sample">Statistics vary from sample to sample</h2>
<p>Recall the original sample statistics which we previously computed:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">btstats</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
    Min   Med     M    SD   Max
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  35.8  36.8  36.8 0.425  38.2</code></pre>
</div>
</div>
<p>If we were to take another sample, the sample mean would be different. Let’s try resampling (with replacement) 50 people:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">btdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/sample_n.html">sample_n</a></span><span class="op">(</span><span class="fl">50</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 2
   BodyTemp Pulse
      &lt;dbl&gt; &lt;dbl&gt;
 1     37.4    77
 2     37.1    64
 3     36.9    70
 4     36.9    82
 5     36.9    83
 6     36.5    77
 7     36.8    73
 8     37.2    81
 9     36.4    74
10     37.2    75
# ℹ 40 more rows</code></pre>
</div>
</div>
<p>Next, compute the mean:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">btdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/sample_n.html">sample_n</a></span><span class="op">(</span><span class="fl">50</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>M <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">BodyTemp</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
      M
  &lt;dbl&gt;
1  36.9</code></pre>
</div>
</div>
<p>Let’s do this many times, 1000 say — leading to 1000 sample means, one for each sample of 50 participants:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">many_means</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span><span class="fl">1000</span>, </span>
<span>                        <span class="va">btdata</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>                          <span class="fu"><a href="https://dplyr.tidyverse.org/reference/sample_n.html">sample_n</a></span><span class="op">(</span><span class="fl">50</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>                          <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>M <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">BodyTemp</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                        simplify <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">many_means</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
# A tibble: 1 × 1
      M
  &lt;dbl&gt;
1  36.8

[[2]]
# A tibble: 1 × 1
      M
  &lt;dbl&gt;
1  36.9

[[3]]
# A tibble: 1 × 1
      M
  &lt;dbl&gt;
1  36.8

[[4]]
# A tibble: 1 × 1
      M
  &lt;dbl&gt;
1  36.7

[[5]]
# A tibble: 1 × 1
      M
  &lt;dbl&gt;
1  36.8

[[6]]
# A tibble: 1 × 1
      M
  &lt;dbl&gt;
1  36.8</code></pre>
</div>
</div>
<aside>
replicate(n, code, simplify = FALSE) runs the code n times, and simplify = FALSE is an option for how the output should be stored (don’t worry about this).
</aside><p>We will now combine into a single tibble the 1000 means, each one computed from a different sample of 50 people:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">many_means</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows</a></span><span class="op">(</span><span class="va">many_means</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">many_means</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1
      M
  &lt;dbl&gt;
1  36.8
2  36.9
3  36.8
4  36.7
5  36.8
6  36.8</code></pre>
</div>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">many_means</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1000    1</code></pre>
</div>
</div>
<p>We now plot the distribution of the sample means. The distribution shows the possible values of the sample mean on the x axis, and how often each value appears on the y axis:</p>
<aside><strong>Distribution</strong><br>
The distribution of a variable tells us what values it takes and how often it takes these values.
</aside><div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">many_means</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">M</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">'white'</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">'Sample mean'</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04-insights-from-data_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of a statistic computed on many resamples is called the <em>sampling distribution</em> of the statistic: it shows the values the statistic can take and how often they appear across many samples.</p>
<aside>
sampling distribution
</aside><p>As you can see, most of the sample means you would obtain from samples of size 50 people would be within 36.7 and 36.9 °C. Only a couple of sample means appear to be around 37 °C.</p>
<p>Many years ago, the statistician William Sealy Gosset — while working as the chief experimental brewer for the Guinness Brewery in Dublin — found a mathematical curve that fits the distribution of the sample mean shown in the histogram above. This is called a <em>t distribution</em> and depends on a number called the <em>degrees of freedom</em> (df) which is simply the sample size minus one: <span class="math inline">\(n - 1\)</span>.<br>
The t distribution with <span class="math inline">\(n-1\)</span> df is written <span class="math inline">\(t(n - 1)\)</span> and in this case as the sample has size <span class="math inline">\(n = 50\)</span>, it is <span class="math inline">\(t(49)\)</span>:</p>
<aside>
t distribution<br>
degrees of freedom
</aside><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04-insights-from-data_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>As you can see above, the distribution of the sample mean follows a t distribution (the red curve above). You don’t need to learn the mathematical formula of the red curve, as R can compute it for you (more on this later).</p>
<p>The width of the distribution is the standard deviation of the sample mean. It has a special name however: <em>standard error</em> of the sample mean, as it tells us how variable the sample means are from sample to sample.<br>
In other words, it tells us how reliable those means are as estimates of the unknown population mean. The smaller the variation (the narrows the distribution), the better.</p>
<aside>
standard error
</aside><p><span class="math display">\[
SE(\text{sample mean}) =
\frac{SD(\text{original sample})}{\sqrt{\text{sample size}}}
\]</span></p>
<p>In this case, the original sample is the collected data <code>btdata</code>. The SE of the mean is computed as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">SD</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">btdata</span><span class="op">$</span><span class="va">BodyTemp</span><span class="op">)</span> <span class="co"># same as btstats$SD</span></span>
<span><span class="va">SD</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4251776</code></pre>
</div>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">btdata</span><span class="op">)</span></span>
<span><span class="va">n</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50</code></pre>
</div>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">SE</span> <span class="op">&lt;-</span> <span class="va">SD</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span></span>
<span><span class="va">SE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0601292</code></pre>
</div>
</div>
<p><span class="math display">\[
SE(\text{mean}) = \frac{0.4251776}{\sqrt{50}} = 0.0601292
\]</span></p>
<p>You can confirm that it is approximately equal to the standard deviation of the 1000 generated sample means. The two numbers for the SE will become closer and closer as the number of resamples increases (from 1,000 to 10,000 or 100,000 for example):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">many_means</span><span class="op">$</span><span class="va">M</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05977689</code></pre>
</div>
</div>
<p>They seen pretty close to me!</p>
<p>To sum up, the sample mean is 36.81 °C, with a standard error of 0.06 °C.</p>
<blockquote class="blockquote">
<p><strong>Think about it</strong><br>
Note that the standard deviation of the original data is 0.43, while the standard deviation of the means is 0.06. That is, the sample means will always be less variable than the original data. This is good! We don’t want our best estimates to vary too much if we had collected a slightly different sample in the first place.</p>
</blockquote>
</section><section id="t-test-for-a-mean" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="t-test-for-a-mean">T-test for a mean</h2>
<p>Recall the sampling distribution of the mean:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04-insights-from-data_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>How can we use this distribution to test whether the unknown mean body temperature for the entire population of healthy individuals is 37 °C?</p>
<p>The answer lies in comparing the difference between the (observed) sample mean and the hypothesised population value to the variability of the sample means due to random sampling.<br>
This is called the <em>t statistic</em> and is computed as:</p>
<aside>
t-statistic
</aside><p><span class="math display">\[
\begin{aligned}
t
&amp;= \frac{\text{pattern}}{\text{noise}} \\
&amp;= \frac{\text{observed - hypothesised mean}}{\text{chance variation due to sampling}} \\
&amp;= \frac{\text{sample mean} - \text{hypothesised mean}}{SE(\text{sample mean})}
\end{aligned}
\]</span></p>
<p>In the formula above, the pattern is the difference between the sample (observed) mean and the hypothesised value in the null hypothesis.</p>
<p>The chance variation due to sampling is quantified by the standard error of the mean. The standard error (SE) is the standard deviation of the sampling distribution of the mean.<br><strong>Careful!</strong> This is NOT the SD of the original sample!</p>
<p>We typically decide that there is “something of interest going on” in the data that is worth reporting to the public if the t statistic is very far from 0, i.e.&nbsp;very large or very negative.<br>
In those cases, <strong>the pattern is larger than the noise due to random sampling alone</strong>, and we say there is evidence against the null hypothesis and in favour of the alternative hypothesis.</p>
<p>On the other hand, if the t statistic is not big enough and fairly close to 0, the denominator in the fraction will be larger than the numerator, meaning that the noise (= natural chance variation due to random sampling) explained most of the variation in the data. In this case we say that there is not sufficient evidence against the null hypothesis and hence we do not reject it. That is, we maintain / fail to reject the status quo.</p>
<blockquote class="blockquote">
<p><strong>Careful!</strong><br>
Not finding sufficient evidence against the null hypothesis is NOT the same as finding evidence FOR the null hypothesis. You simply might not have enough data to assess whether the alternative hypothesis might be the correct one. So, because of not having enough data, you cannot distinguish which one of <span class="math inline">\(H_0\)</span> or <span class="math inline">\(H_1\)</span> is true. The test is inconclusive. Hence, the community agrees to use a conservative approach and maintain the null hypothesis.</p>
</blockquote>
<p>Let’s compute the t-statistic in our sample:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">M</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">btdata</span><span class="op">$</span><span class="va">BodyTemp</span><span class="op">)</span></span>
<span><span class="va">M</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 36.81111</code></pre>
</div>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">Hyp</span> <span class="op">&lt;-</span> <span class="fl">37</span></span>
<span><span class="va">Hyp</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37</code></pre>
</div>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">SE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0601292</code></pre>
</div>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tstat</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">M</span> <span class="op">-</span> <span class="va">Hyp</span><span class="op">)</span> <span class="op">/</span> <span class="va">SE</span></span>
<span><span class="va">tstat</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -3.141384</code></pre>
</div>
</div>
<p><span class="math display">\[
t
= \frac{36.81111 - 37}{0.0601292}
= -3.141384
\]</span></p>
<p>R does the computation above for you. So from now on, use R to do tests.</p>
<p>The call of the function is</p>
<pre><code>t.test(&lt;numeric vector&gt;, mu = &lt;hypothesis&gt;, alternative = &lt;direction&gt;)</code></pre>
<p>where</p>
<ul>
<li><p>numeric vector should be the extracted column from the data table with the data;</p></li>
<li><p>mu is the hypothesised value in the null hypothesis;</p></li>
<li><p>alternative is the sign in the alternative hypothesis: ‘two.sided’ for <span class="math inline">\(\neq\)</span>, ‘less’ for <span class="math inline">\(&gt;\)</span> and ‘greater’ for <span class="math inline">\(&gt;\)</span>.</p></li>
</ul>
<p>The result is:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">btdata</span><span class="op">$</span><span class="va">BodyTemp</span>, mu <span class="op">=</span> <span class="fl">37</span>, alternative <span class="op">=</span> <span class="st">'two.sided'</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  btdata$BodyTemp
t = -3.1414, df = 49, p-value = 0.002851
alternative hypothesis: true mean is not equal to 37
95 percent confidence interval:
 36.69028 36.93195
sample estimates:
mean of x 
 36.81111 </code></pre>
</div>
</div>
<p>The output gives us everything we need:</p>
<ul>
<li><p><code>t = -3.1414</code>: the t-statistic</p></li>
<li><p><code>df = 49</code>: the degrees of freedom = sample size - 1 = 50 - 1 = 49</p></li>
<li><p><code>alternative hypothesis: true mean is not equal to 37</code>: a reminder that the alternative hypothesis is <span class="math inline">\(H_1 : \mu \neq 37 °C\)</span>.</p></li>
<li><p>A reminder that the sample mean in the original sample was 36.81111<br><code>mean of x</code><br><code>36.81111</code></p></li>
</ul>
<p>As well as extra information:</p>
<ul>
<li><p><code>p-value = 0.002851</code></p></li>
<li><p><code>95 percent confidence interval:</code> <code>36.69028 36.93195</code></p></li>
</ul></section><section id="p-value" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="p-value">P-value</h2>
<p>The p-value is a measure of the strength of evidence that the data bring against the null hypothesis and in favour of the alternative hypothesis.</p>
<p>It is defined as the probability of obtaining sample results as extreme as, or more extreme than, the observed ones if the null hypothesis was true.</p>
<aside>
p-value
</aside><blockquote class="blockquote">
<p><strong>Understanding the p-value</strong><br>
Imagine a world where the null hypothesis <span class="math inline">\(H_0 : \mu = 37 °C\)</span> is true — that is, the true mean body temperature for all healthy adults is 37 °C.<br>
Now, imagine obtaining many thousands of resamples, each of size 50, from the population. Each sample will have a sample mean and we can then plot the distribution of means.<br>
This distribution is special, it was created assuming the null hypothesis to be true, and so it shows us the values of the sample mean we would expect if the null hypothesis was true in the population. It is important to notice that it is centred at the hypothesised value, in this case 37 °C.<br>
The proportion of means in that distribution that are more distant to the hypothesised value (in either direction) than the actual sample mean obtained (36.81111) is the p-value.</p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04-insights-from-data_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The p-value is an important measure that science has used since the 1900s to quantify when the evidence that the data bring in favour of the alternative hypothesis is strong enough that it cannot simply be due to the variation in means due to random sampling (called natural variation), but it quantifies if there is “something else” going on, and that something else is the pattern of interest.</p>
<blockquote class="blockquote">
<p><strong>Guidelines for evaluating strength of evidence from p-values:</strong></p>
<ul>
<li><p>0.10 &lt; p-value<br>
not much evidence against null hypothesis; null is plausible</p></li>
<li><p>0.05 &lt; p-value <span class="math inline">\(\leq\)</span> 0.10<br>
moderate evidence against the null hypothesis</p></li>
<li><p>0.01 &lt; p-value <span class="math inline">\(\leq\)</span> 0.05<br>
strong evidence against the null hypothesis</p></li>
<li><p>p-value <span class="math inline">\(\leq\)</span> 0.01<br>
very strong evidence against the null hypothesis</p></li>
</ul>
<p><em>The smaller the p-value, the stronger the evidence against the null hypothesis.</em></p>
</blockquote>
<p>The p-values should be reported IN FULL — that is, with all its decimal places — unless it’s very very tiny, such as smaller than 0.001. In such cases the reader won’t be interested to the 6th or 7th decimal, so you can simply write p &lt; 0.001.</p>
<p>At the end of an analysis we may need to make a decision / recommend an action to policy makers. To actually make a decision there are some commonly used cutoffs for the p-value that are used to decide whether or not to reject the null hypotehsis. Typical values for this threshold are 0.05 or 0.01, depending on how strict you want to be. The threshold or cutoff value is called the <em>significance level</em> and is denoted by the greek letter <span class="math inline">\(\alpha\)</span>.</p>
<p>The scientific investigation process requires you to decide on the significance level in advance, before analysing any data, and to clearly state it at the beginning of your reporting for the reader, as this chosen significance level will affect in all that will follow whether your results will be interpreted as significant or not.</p>
<aside>
significance level
</aside><p>In our example, we would write up the results as follows:</p>
<p>At the 5% significance level, we performed a two-sided t-test against the null hypothesis that the mean body temperature for healthy humans is 37 °C (<span class="math inline">\(t(49) = -3.141\)</span>, <span class="math inline">\(p = 0.003\)</span>, two-sided). If the population mean body temperature was truly equal to 37 °C, the probability of obtaining a sample with a mean as extreme as, or more extreme than the obtained one (36.811) would be 3 in 1,000. In other words, only 3 samples out of 1,000 would have a mean as extreme as 36.811. The sample results provide very strong evidence that the population mean body temperature for healthy individuals is now different from 37 °C.</p>
</section><section id="confidence-interval" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="confidence-interval">Confidence interval</h2>
<p>If is important to always follow up a significant hypothesis test with a confidence interval.</p>
<p>A confidence interval gives you a range of plausible value for the unknown parameter your are interested in. It is linked to the significance level <span class="math inline">\(\alpha\)</span> in the sense that if <span class="math inline">\(\alpha = 0.05\)</span>, then the confidence interval is a 95% confidence interval. If <span class="math inline">\(\alpha = 0.01\)</span>, the confidence interval is a 99% confidence interval.</p>
<aside>
confidence interval
</aside><p>A 95% confidence interval (CI) gives you the range of values in the sampling distribution of the statistic (the mean in this case) that includes 95% of all sample means</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04-insights-from-data_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Recall the output from the <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> function:</p>
<pre><code>95 percent confidence interval:
 36.69028 36.93195</code></pre>
<p>We are 95% confident that the mean body temperature for all healthy humans is between 36.69 °C and 36.93 °C.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="CIs and hypothesis tests">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CIs and hypothesis tests
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There is a deep link between confidence intervals and hypothesis tests. A confidence interval gives the range of plausible values that an unknown parameter of interest can take. A test of hypotheses checks whether an hypothesised value for the population parameter is plausible in light of the collected sample data.<br>
If your hypothesised value in <span class="math inline">\(H_0\)</span> lies inside the 95% confidence interval, then it is a plausible value for the population parameter and an hypothesis test at the 5% significance level will fail to reject the null.<br>
If your hypothesised value in <span class="math inline">\(H_0\)</span> falls outside the 95% confidence interval, then it is not a plausible value for the population parameter and an hypothesis test at the 5% significance level will reject the null.<br>
However, a CI does not tell you anything about the <em>strength of evidence</em> against the null hypothesis that the sample data bring. This is quantified by the p-value, provided by a test of hypotheses. Simply saying the hypothesised value is outside of the CI, it doesn’t tell you <em>how far</em> from the boundary it is. The furthest, the stronger the evidence, and this is why we also report p-values.</p>
</div>
</div>
</div>
</section><section id="effect-size-cohens-d" class="level2"><h2 class="anchored" data-anchor-id="effect-size-cohens-d">Effect size: Cohen’s D</h2>
<p>Sometimes you may obtain a significant result, and think: “wow, amazing, I have made an impressive discovery!”</p>
<p>Hang on, it’s not that simple. Statistical significance does not guarantee practical significance or importance. These are two distinct concepts which should be understood. A common misunderstanding is thinking that significant has the same meaning as important. In science this is not the same!</p>
<ul>
<li><p>“Significant” means “Statistically significant”.<br>
A statistical significant result means that it is unlikely to happen just by random chance alone.</p></li>
<li><p>“Important” means “Practically important”.<br>
This means that the difference is large enough to matter in the real world and to decision makers.</p></li>
</ul>
<p>To be clear, always use the adjective: statistically significant, practically important.</p>
<blockquote class="blockquote">
<p><strong>Think about it</strong><br>
Does the fact that the true mean body temperature for all healthy humans in the population lies somewhere in between 36.69 °C and 36.93 °C, and in particular our best estimate 36.81 °C which was the sample mean, have any practical impact for decisions makers? Is it really such a big chance from the well-established 37 °C?</p>
</blockquote>
<p>Especially with large sample sizes, even a fairly small difference between an observed and hypothesized value can be statistically significant. In such cases a confidence interval for the parameter can help to decide whether the difference is practically important.</p>
<p>Alternatively, to quantify whether a difference between an observed and hypothesised value is important, in Psychology it is common to report also the effect size, also known as Cohen’s D.</p>
<p>First, install the <code>effectsize</code> package:</p>
<pre><code>install.packages("effectsize")</code></pre>
<p>Then use it as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://easystats.github.io/effectsize/">effectsize</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://easystats.github.io/effectsize/reference/cohens_d.html">cohens_d</a></span><span class="op">(</span><span class="va">btdata</span><span class="op">$</span><span class="va">BodyTemp</span>, mu <span class="op">=</span> <span class="fl">37</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |         95% CI
--------------------------
-0.44     | [-0.73, -0.15]

- Deviation from a difference of 37.</code></pre>
</div>
</div>
<p>The interpretation of whether the difference is of practical importance follows these heuristic cutoffs which were recommended by the author following extensive empirical investigations:</p>
<table class="table">
<thead><tr class="header">
<th>Cohen’s D</th>
<th>Effect size</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>
<span class="math inline">\(\leq\)</span> 0.20</td>
<td>Small</td>
</tr>
<tr class="even">
<td>
<span class="math inline">\(\approx\)</span> 0.50</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td>
<span class="math inline">\(\geq\)</span> 0.80</td>
<td>Large</td>
</tr>
</tbody>
</table>
<p>In this case we are in the presence of a small effect, reinforcing that even if the results were statistical significance, i.e.&nbsp;unlikely to be due to random sampling variation alone, they are not of practical importance due to the very samll difference between the observed and hypothesised values.</p>
</section><section id="validity-conditions-of-the-t-test" class="level2"><h2 class="anchored" data-anchor-id="validity-conditions-of-the-t-test">Validity conditions of the t-test</h2>
<p>The conditions to satisfy for the CIs and p-values from the t-test to be trustworthy are as follows:</p>
<ol type="1">
<li><p>Data should be a simple random sample from population of interest</p></li>
<li><p>Either one of 2a or 2b holds:<br><br> 2a) The original sample follows a normal distribution. (This is a distribution similar to the t, and you do this test with the <code><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test()</a></code> function in R.)<br><br> Or:<br><br> 2b) You should have at least 30 observations in the sample, and the distribution of the data should not have strong outliers or be strongly skewed.</p></li>
</ol>
<blockquote class="blockquote">
<p><em>Note.</em><br>
It’s important to keep in mind that the above conditions are rough guidelines and not a guarantee.</p>
</blockquote>
<p>Let’s check each in turn:</p>
<ol type="1">
<li><p>The problem description says the data were collected on a random sample of 50 healthy subjects.</p></li>
<li><p>Let’s start by checking 2a:</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">btdata</span><span class="op">$</span><span class="va">BodyTemp</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  btdata$BodyTemp
W = 0.97322, p-value = 0.3115</code></pre>
</div>
</div>
<p>The p-value is 0.31, which is larger than the chosen significance level of 5%, hence we do not reject the null hypothesis that the sample came from a normal distribution. The conditions for the validity of the t-test results are met.</p>
<p>We could then stop here. However, since this is to show you how to do everything, you would check 2b as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">btdata</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50  2</code></pre>
</div>
</div>
<p>The sample size is 50, which is larger than 30.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">btdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">BodyTemp</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">'white'</span><span class="op">)</span> <span class="op">+</span></span>
<span>     <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">'darkorange'</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04-insights-from-data_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of the data is roughly simmetric, with no strong outliers. The boxplot highlights one data point as an outlier, but the gap could easily be due to the sample size.</p>
</section><section id="recommended-activities" class="level2"><h2 class="anchored" data-anchor-id="recommended-activities">Recommended activities</h2>
<ul>
<li><a href="https://posit.cloud/learn/primers/3.1">4.1 Exploratory Data Analysis</a></li>
<li><a href="https://posit.cloud/learn/primers/3.2">4.2 Bar Charts</a></li>
<li><a href="https://posit.cloud/learn/primers/3.3">4.3 Histograms</a></li>
<li><a href="https://posit.cloud/learn/primers/3.4">4.4 Boxplots and counts</a></li>
</ul>


</section><a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>
<ol>
<li id="fn1"><p>Shoemaker, A. L. (1996). <em>What’s Normal: Temperature, Gender and Heartrate. Journal of Statistics Education, 4</em>(2), 4.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./03-exploring-data.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">3: Exploring data</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-making-decisions.html" class="pagination-link">
        <span class="nav-page-text">5: Making decisions</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>